trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- script: yarn install
  displayName: 'Install App'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- script: yarn build
  displayName: 'Build'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- script: yarn build
  displayName: 'Build Retry'
  condition: and(failed(), ne(variables['Build.Reason'], 'PullRequest'))

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'public'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
